### ISSUE TITLE
Instruction of building the module

### ISSUE THREAD

**Issue by szebrowski** [tylpk1216/kobo-libra2-uhid-module#1]
Hi, I am on the latest FW, 4.32.* and I think because of that I cannot make to work my bt keyboard. Can you provide instruction for building the module? :)

btw. SUPER COOL WORK, thanks :)

**Comment by tylpk1216** [comment]
I use the concept of  below site to build the uhid.ko.
[https://blukat.me/2017/12/cross-compile-arm-kernel-module/](https://blukat.me/2017/12/cross-compile-arm-kernel-module/)

Just remember to copy /proc/config.gz from your device.
By the way, I use Windows 10 WSL + Docker Desktop to build the uhid.ko.
[https://youtu.be/eSjBcCf5axo](https://youtu.be/eSjBcCf5axo)

If you need more steps, please let me know.

**Comment by szebrowski** [comment]
what's the easiest way to copy /proc/config.gz ? :)

**Comment by tylpk1216** [comment]
There is no easy way to copy /proc/config.gz. However, I use NickelMenu to telnet into the device.
```
menu_item :main    :Telnet (toggle)          :cmd_output         :500:quiet :/usr/bin/pkill -f "^/usr/bin/tcpsvd -E 0.0.0.0 1023"
  chain_success:skip:5
  chain_failure                              :cmd_spawn          :quiet :/bin/mount -t devpts | /bin/grep -q /dev/pts || { /bin/mkdir -p /dev/pts && /bin/mount -t devpts devpts /dev/pts; }
  chain_success                              :cmd_spawn          :quiet :exec /usr/bin/tcpsvd -E 0.0.0.0 1023 /usr/sbin/telnetd -i -l /bin/login
  chain_success                              :dbg_toast          :Started Telnet server on port 1023
  chain_failure                              :dbg_toast          :Error starting Telnet server on port 1023
  chain_always:skip:-1
  chain_success                              :dbg_toast          :Stopped Telnet server on port 1023
```
The user name is "root". The password is empty.

When you telnet into the device, you can use cp command to copy the config.gz.
```
cp /proc/config.gz /mnt/onboard/
```

Then you can use PC to get the file.

By the way, I use oldconfig parameter to build kernel so I use text editor to edit the extracted config (from config.gz) to add uhid module support.
```
CONFIG_UHID=m
```

I don't try this yet, However, make can support the ko target rule (from Makefile) in theory.
```
make ARCH=arm CROSS_COMPILE=<TOOLCHAIN_DIR>/bin/arm-linux-gnueabihf- drivers/hid/uhid.ko
```

**Comment by tylpk1216** [comment]
I add steps to build the kernel, you could refer to README.md.

**Comment by tocklime** [comment]
Just a note to say that building just `drivers/hid/uhid.ko` appeared to work for me, but the resulting file failed when I ran `insmod` on it on the kobo. Building the whole tree produced a `uhid.ko` that inserted ok (now I just need to figure out what /other/ config setting I need to get the bluetooth device I've got working....)
