### ISSUE TITLE
Instructions for Clara 2E

### ISSUE THREAD

**Issue by jmacindoe** [tylpk1216/kobo-libra2-uhid-module#2]
Hey awesome work!

Just letting you know that I've adapted your instructions to work with the Kobo Clara 2E. I've put them in a new repo here https://github.com/jmacindoe/kobo-kernel-modules. I needed to use the Rakuten modified source code to get modules other than uhid.ko working, but otherwise followed your instructions exactly. I'm hoping to build up a collection of kernel modules for Kobo devices at the new repo. I've put up instructions for the LIbra 2 but don't actually own one https://github.com/jmacindoe/kobo-kernel-modules/tree/main/Kobo%20Mark%209%20-%20Libra%202. If you could share your Libra 2 config.gz with me and/or test out my modules that'd be awesome! But no obligation obviously.

Thanks :D

**Comment by tylpk1216** [comment]
Sorry for late reply. After I tested this project on Libra 2, I sold the device. I don't have config.gz now. Anyway, this is a good news that it works on your Clare 2E.
