### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by bilogic** [tylpk1216/kobo-libra2-uhid-module#3]
I have a BT device connected to my Kobo Libra 2 that is not `/dev/input/eventX`. Any idea how I can make `eventX` show up?

**Comment by bilogic** [comment]
Find another device.

**Comment by tylpk1216** [comment]
Sorry for late reply.  I think the support of BT on some Kobo devies is not good as Kobo Elipsa.  I am glad to hear that you have solved your problem.
